### ISSUE TITLE
Headers should be matched case insensitive

### ISSUE THREAD

**Issue by danyowdee** [q231950/the-stubborn-network#15]
HTTP headers are case insensitive.
So the following should take care of normalising case:
 https://github.com/q231950/the-stubborn-network/blob/b6ec08109dc0defc3c932ffdac62cb07397db8d4/Sources/StubbornNetwork/PersistentStubSource.swift#L103

(In addition, I am undecided whether header matching should really be this strict: the current implementation requires all of them to be set, and — if a header is set multiple times — in an exact order, which makes the stubs more fragile than necessary. Because the correct matching policy is highly context sensitive, addressing that would be way beyond the scope of this issue, as it would probably require the introduction of matcher objects.)

**Comment by danyowdee** [comment]
Meh: case of `key`, that is.

**Comment by q231950** [comment]
@danyowdee many thanks for adding this issue. Much appreciated! 

I have some questions to clarify.

1.

> requires all of them to be set

You mean this would be too much work for the person who wants to stub?

2.

> if a header is set multiple times — in an exact order

Can you give an example, I cannot quite follow, I think that the [sorting of the one request](https://github.com/q231950/the-stubborn-network/blob/b6ec08109dc0defc3c932ffdac62cb07397db8d4/Sources/StubbornNetwork/PersistentStubSource.swift#L104) and the [sorting of the other](https://github.com/q231950/the-stubborn-network/blob/b6ec08109dc0defc3c932ffdac62cb07397db8d4/Sources/StubbornNetwork/PersistentStubSource.swift#L110) would prevent exactly that.

3.

> case of key, that is.

you mean the header names (keys) should be case insensitive only?

**Comment by q231950** [comment]
@danyowdee I think that matcher objects will be inevitable at a certain point once support for delayed responses or filtered/regex'ed requests is needed.

Please see if the referenced draft pull request #17 is what you had in mind as a first step.

**Comment by danyowdee** [comment]
To answer the questions:

3.
Yes, HTTP treats header names (so the keys in this dictionary) as case insensitive, and so should the matching. (Edit: as you did in #17.)

2. (and 1.)
Because HTTP headers are rather `Array<HTTPHeader>` than  `Dictionary<CaseInsensitiveString, String>`, flattening that array correctly is not quite straight forward. Most importantly, you can have the same header repeatedly — see `URLRequest`’s `addValue(_:, forHTTPHeaderField:)` — which ends up in a CSV string. And so the matching becomes order dependent: you expect an exact match on the CSV of one value where HTTP doesn’t/a server would be fine with a subexpression match, or an unordered match.

**Comment by q231950** [comment]
> the matching becomes order dependent

This is true and is now written in stone with [testHeaderOrderMismatches](https://github.com/q231950/the-stubborn-network/pull/17/files#diff-48490b5299099333aa4ce0bede08486fR45-R54). The fact that a server might accept differently ordered headers is okay I think since the matching is used by **The Stubborn Network** internally to find its stubs.

I added the [case insensitive](https://github.com/q231950/the-stubborn-network/pull/17/files#diff-309e555a735cda454a82595139d6c51fR113) header comparison as you had seen it, refactored the method a bit for easier testing and added a few tests for the current behaviour.

@danyowdee thanks again for bringing this up! If you see anything else, [let me know](https://github.com/q231950/the-stubborn-network/issues/new) 😃
